'use client';

import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';

// Professional SVG Icons
const Icons = {
  Points: () => (
    <svg className="w-8 h-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Heart: () => (
    <svg className="w-8 h-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path strokeLinecap="round" strokeLinejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
    </svg>
  ),
  Verification: () => (
    <svg className="w-8 h-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
    </svg>
  ),
  Contact: () => (
    <svg className="w-8 h-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path strokeLinecap="round" strokeLinejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
    </svg>
  ),
};

export default function PartnersPage() {
  // Scroll animation refs
  const pointsRef = useRef<HTMLDivElement>(null);
  const verificationRef = useRef<HTMLDivElement>(null);
  const partnersRef = useRef<HTMLDivElement>(null);
  const contactRef = useRef<HTMLDivElement>(null);

  // Visibility states
  const [pointsVisible, setPointsVisible] = useState(false);
  const [verificationVisible, setVerificationVisible] = useState(false);
  const [partnersVisible, setPartnersVisible] = useState(false);
  const [contactVisible, setContactVisible] = useState(false);

  // Intersection Observer for scroll animations
  useEffect(() => {
    const observerOptions = {
      root: null,
      rootMargin: '0px',
      threshold: 0.15,
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          if (entry.target === pointsRef.current) setPointsVisible(true);
          if (entry.target === verificationRef.current) setVerificationVisible(true);
          if (entry.target === partnersRef.current) setPartnersVisible(true);
          if (entry.target === contactRef.current) setContactVisible(true);
        }
      });
    }, observerOptions);

    const refs = [pointsRef, verificationRef, partnersRef, contactRef];
    refs.forEach((ref) => {
      if (ref.current) observer.observe(ref.current);
    });

    return () => observer.disconnect();
  }, []);

  return (
    <div className="min-h-screen flex flex-col bg-white dark:bg-slate-900">
      <Header />

      <main className="flex-1">
        {/* Hero Section */}
        <section className="bg-gradient-to-br from-[#5B7B6D] to-[#2D5A4A] text-white">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 md:py-28">
            <div className="max-w-4xl">
              <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-white/20 text-white rounded-full text-sm font-medium mb-6">
                <span className="w-2 h-2 bg-white rounded-full animate-pulse" />
                For Charities & Partners
              </div>
              <h1 className="font-serif text-4xl md:text-5xl lg:text-6xl font-bold mb-6 leading-tight">
                Turn Student Wellness Into{' '}
                <span className="text-[#C4A77D]">Real-World Impact</span>
              </h1>
              <p className="text-xl text-[#E8E0D5] mb-8 max-w-3xl">
                Partner with TribeWellMD to receive donations generated by medical students through their study and wellness activities.
                Every flashcard reviewed, every wellness challenge completed creates charitable impact.
              </p>
              <div className="flex flex-wrap gap-4">
                <a
                  href="mailto:partners@tribewellmd.com"
                  className="px-8 py-4 bg-gradient-to-r from-[#C4A77D] to-[#A89070] text-white font-bold rounded-xl hover:shadow-xl transition-all shadow-lg"
                >
                  Become a Partner
                </a>
                <Link
                  href="/impact"
                  className="px-8 py-4 border-2 border-white/50 text-white font-semibold rounded-xl hover:bg-white/10 transition-all"
                >
                  See Our Impact
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* How It Works - Points Economy */}
        <section ref={pointsRef} className="bg-white dark:bg-slate-900 py-16 md:py-24">
          <div className={`max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 transition-all duration-700 ${pointsVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
            <div className="flex items-start gap-4 mb-8">
              <div className="w-14 h-14 rounded-xl bg-[#E8E0D5] dark:bg-[#5B7B6D]/30 flex items-center justify-center text-[#5B7B6D] dark:text-[#C4A77D] flex-shrink-0">
                <Icons.Points />
              </div>
              <div>
                <h2 className="font-serif text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-2">
                  How Points Become Donations
                </h2>
                <p className="text-slate-600 dark:text-slate-400 text-lg">Transparent economics that scale with our community</p>
              </div>
            </div>

            {/* Conversion Table */}
            <div className="bg-slate-50 dark:bg-slate-800 rounded-2xl shadow-lg overflow-hidden mb-8">
              <div className="p-4 bg-slate-100 dark:bg-slate-700 border-b border-slate-200 dark:border-slate-600">
                <h3 className="font-semibold text-slate-900 dark:text-white">Points-to-Donation Conversion</h3>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-slate-200 dark:border-slate-700">
                      <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700 dark:text-slate-300">Activity</th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700 dark:text-slate-300">XP Earned</th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-slate-700 dark:text-slate-300">Village Points</th>
                      <th className="px-6 py-4 text-left text-sm font-semibold text-[#5B7B6D] dark:text-[#C4A77D]">Donation Value</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200 dark:divide-slate-700">
                    <tr>
                      <td className="px-6 py-4 text-sm text-slate-900 dark:text-white">Flashcard review</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">5-12 XP</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">~1 point</td>
                      <td className="px-6 py-4 text-sm text-[#5B7B6D] dark:text-[#C4A77D] font-medium">$0.001</td>
                    </tr>
                    <tr className="bg-white dark:bg-slate-800/50">
                      <td className="px-6 py-4 text-sm text-slate-900 dark:text-white">Clinical case completion</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">25-40 XP</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">2-4 points</td>
                      <td className="px-6 py-4 text-sm text-[#5B7B6D] dark:text-[#C4A77D] font-medium">$0.002-0.004</td>
                    </tr>
                    <tr>
                      <td className="px-6 py-4 text-sm text-slate-900 dark:text-white">10,000 steps (verified)</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">50 XP</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">5 points</td>
                      <td className="px-6 py-4 text-sm text-[#5B7B6D] dark:text-[#C4A77D] font-medium">$0.005</td>
                    </tr>
                    <tr className="bg-white dark:bg-slate-800/50">
                      <td className="px-6 py-4 text-sm text-slate-900 dark:text-white">Healthy meal photo</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">20 XP</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">2 points</td>
                      <td className="px-6 py-4 text-sm text-[#5B7B6D] dark:text-[#C4A77D] font-medium">$0.002</td>
                    </tr>
                    <tr>
                      <td className="px-6 py-4 text-sm text-slate-900 dark:text-white font-medium">7-day streak bonus</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">100 XP</td>
                      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400">10 points</td>
                      <td className="px-6 py-4 text-sm text-[#5B7B6D] dark:text-[#C4A77D] font-medium">$0.01</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {/* Scale projection */}
            <div className="bg-gradient-to-r from-[#5B7B6D] to-[#2D5A4A] rounded-2xl p-6 md:p-8 text-white">
              <h3 className="font-bold text-xl mb-4">Projected Impact at Scale</h3>
              <div className="grid md:grid-cols-4 gap-6">
                <div>
                  <div className="text-3xl font-bold mb-1">1,000</div>
                  <p className="text-[#E8E0D5]">active students</p>
                </div>
                <div>
                  <div className="text-3xl font-bold mb-1">50,000</div>
                  <p className="text-[#E8E0D5]">points/week</p>
                </div>
                <div>
                  <div className="text-3xl font-bold mb-1">$50/week</div>
                  <p className="text-[#E8E0D5]">to charity pool</p>
                </div>
                <div>
                  <div className="text-3xl font-bold mb-1">$2,600/year</div>
                  <p className="text-[#E8E0D5]">per 1K students</p>
                </div>
              </div>
              <div className="mt-6 p-4 bg-white/10 rounded-xl">
                <p className="text-sm text-[#E8E0D5]">
                  <strong className="text-white">Multiplier Effect:</strong> Institutional sponsors (medical schools, hospitals) can match student contributions 10-20x.
                  A medical school partnership could generate $25,000-50,000+ annually for charity partners.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Activity Verification System */}
        <section ref={verificationRef} className="bg-gradient-to-b from-[#F5F0E8] to-[#E8E0D5] dark:from-slate-800/50 dark:to-slate-900 py-16 md:py-24">
          <div className={`max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 transition-all duration-700 ${verificationVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
            <div className="flex items-start gap-4 mb-8">
              <div className="w-14 h-14 rounded-xl bg-[#E8E0D5] dark:bg-[#5B7B6D]/30 flex items-center justify-center text-[#5B7B6D] dark:text-[#C4A77D] flex-shrink-0">
                <Icons.Verification />
              </div>
              <div>
                <h2 className="font-serif text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-2">
                  Activity Verification
                </h2>
                <p className="text-slate-600 dark:text-slate-400 text-lg">Ensuring authentic engagement with tiered verification</p>
              </div>
            </div>

            <div className="grid md:grid-cols-3 gap-6">
              {/* Tier 1 */}
              <div className="p-6 bg-white dark:bg-slate-800 rounded-2xl border-2 border-slate-200 dark:border-slate-700 shadow-lg">
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-slate-200 dark:bg-slate-700 rounded-full text-sm font-medium text-slate-700 dark:text-slate-300 mb-4">
                  Tier 1: Self-Reported
                </div>
                <h3 className="font-bold text-lg text-slate-900 dark:text-white mb-3">Base Points</h3>
                <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-400 mb-4">
                  <li>• Honor system activities</li>
                  <li>• Meditation, journaling, hydration</li>
                  <li>• Lower point value (5 pts/activity)</li>
                  <li>• Daily cap to prevent abuse</li>
                </ul>
                <p className="text-xs text-slate-500 dark:text-slate-500 italic">
                  Message: "We trust you. Self-care is about your growth."
                </p>
              </div>

              {/* Tier 2 */}
              <div className="p-6 bg-[#F5F0E8] dark:bg-[#5B7B6D]/20 rounded-2xl border-2 border-[#C4A77D] dark:border-[#8B7355] shadow-lg">
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-[#C4A77D] dark:bg-[#8B7355] rounded-full text-sm font-medium text-white mb-4">
                  Tier 2: Soft Verification
                </div>
                <h3 className="font-bold text-lg text-slate-900 dark:text-white mb-3">Bonus Points (2-3x)</h3>
                <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-400 mb-4">
                  <li>• Photo evidence analyzed by AI</li>
                  <li>• Time-stamped metadata check</li>
                  <li>• Healthy meals, workouts, groups</li>
                  <li>• AI verifies content authenticity</li>
                </ul>
                <p className="text-xs text-[#5B7B6D] dark:text-[#C4A77D] font-medium">
                  Coming in Phase 2
                </p>
              </div>

              {/* Tier 3 */}
              <div className="p-6 bg-gradient-to-br from-[#F5F0E8] to-[#E8E0D5] dark:from-[#5B7B6D]/20 dark:to-[#2D5A4A]/20 rounded-2xl border-2 border-[#C4A77D] dark:border-[#A89070] shadow-lg">
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-gradient-to-r from-[#C4A77D] to-[#A89070] rounded-full text-sm font-medium text-white mb-4">
                  Tier 3: Hard Verification
                </div>
                <h3 className="font-bold text-lg text-slate-900 dark:text-white mb-3">Premium Points (3-5x)</h3>
                <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-400 mb-4">
                  <li>• Apple Health / Google Fit / Fitbit</li>
                  <li>• Actual step counts, sleep data</li>
                  <li>• Workout minutes verification</li>
                  <li>• GPS data (optional, privacy-first)</li>
                </ul>
                <p className="text-xs text-[#8B7355] dark:text-[#C4A77D] font-medium">
                  The Gold Standard - Highest Trust
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Charity Partnerships */}
        <section ref={partnersRef} className="bg-white dark:bg-slate-900 py-16 md:py-24">
          <div className={`max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 transition-all duration-700 ${partnersVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
            <div className="flex items-start gap-4 mb-8">
              <div className="w-14 h-14 rounded-xl bg-[#E8E0D5] dark:bg-[#5B7B6D]/30 flex items-center justify-center text-[#5B7B6D] dark:text-[#C4A77D] flex-shrink-0">
                <Icons.Heart />
              </div>
              <div>
                <h2 className="font-serif text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-2">
                  Partner Organizations
                </h2>
                <p className="text-slate-600 dark:text-slate-400 text-lg">Curated + Custom Hybrid Model</p>
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-8 mb-8">
              <div>
                <h3 className="font-bold text-lg text-slate-900 dark:text-white mb-4">Launch Partners (Pre-verified)</h3>
                <ul className="space-y-4">
                  <li className="flex items-start gap-4 p-4 bg-slate-50 dark:bg-slate-800 rounded-xl">
                    <div className="w-10 h-10 rounded-lg bg-[#E8E0D5] dark:bg-[#5B7B6D]/30 flex items-center justify-center text-[#5B7B6D] dark:text-[#C4A77D] flex-shrink-0">
                      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                      </svg>
                    </div>
                    <div>
                      <p className="font-medium text-slate-900 dark:text-white">Physician Wellness</p>
                      <p className="text-sm text-slate-600 dark:text-slate-400">Dr. Lorna Breen Heroes Foundation</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-4 p-4 bg-slate-50 dark:bg-slate-800 rounded-xl">
                    <div className="w-10 h-10 rounded-lg bg-[#E8E0D5] dark:bg-[#5B7B6D]/30 flex items-center justify-center text-[#5B7B6D] dark:text-[#C4A77D] flex-shrink-0">
                      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                      </svg>
                    </div>
                    <div>
                      <p className="font-medium text-slate-900 dark:text-white">Mental Health</p>
                      <p className="text-sm text-slate-600 dark:text-slate-400">NAMI (National Alliance on Mental Illness)</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-4 p-4 bg-slate-50 dark:bg-slate-800 rounded-xl">
                    <div className="w-10 h-10 rounded-lg bg-[#E8E0D5] dark:bg-[#5B7B6D]/30 flex items-center justify-center text-[#5B7B6D] dark:text-[#C4A77D] flex-shrink-0">
                      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </div>
                    <div>
                      <p className="font-medium text-slate-900 dark:text-white">Healthcare Access</p>
                      <p className="text-sm text-slate-600 dark:text-slate-400">Remote Area Medical, Partners in Health</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-4 p-4 bg-slate-50 dark:bg-slate-800 rounded-xl">
                    <div className="w-10 h-10 rounded-lg bg-[#E8E0D5] dark:bg-[#5B7B6D]/30 flex items-center justify-center text-[#A89070] dark:text-[#C4A77D] flex-shrink-0">
                      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                      </svg>
                    </div>
                    <div>
                      <p className="font-medium text-slate-900 dark:text-white">Medical Education</p>
                      <p className="text-sm text-slate-600 dark:text-slate-400">SNMA, medical student scholarships</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-4 p-4 bg-slate-50 dark:bg-slate-800 rounded-xl">
                    <div className="w-10 h-10 rounded-lg bg-[#E8E0D5] dark:bg-[#5B7B6D]/30 flex items-center justify-center text-[#5B7B6D] dark:text-[#C4A77D] flex-shrink-0">
                      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
                      </svg>
                    </div>
                    <div>
                      <p className="font-medium text-slate-900 dark:text-white">Global Health</p>
                      <p className="text-sm text-slate-600 dark:text-slate-400">Doctors Without Borders / MSF</p>
                    </div>
                  </li>
                </ul>
              </div>

              <div>
                <h3 className="font-bold text-lg text-slate-900 dark:text-white mb-4">Benefits of Partnership</h3>
                <ul className="space-y-3 text-slate-600 dark:text-slate-400 mb-6">
                  <li className="flex items-center gap-3">
                    <svg className="w-5 h-5 text-[#5B7B6D] flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span>501(c)(3) verification required</span>
                  </li>
                  <li className="flex items-center gap-3">
                    <svg className="w-5 h-5 text-[#5B7B6D] flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span>Monthly donation reports & transparency</span>
                  </li>
                  <li className="flex items-center gap-3">
                    <svg className="w-5 h-5 text-[#5B7B6D] flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span>Co-marketing opportunities with medical students</span>
                  </li>
                  <li className="flex items-center gap-3">
                    <svg className="w-5 h-5 text-[#5B7B6D] flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span>Featured on community impact dashboard</span>
                  </li>
                  <li className="flex items-center gap-3">
                    <svg className="w-5 h-5 text-[#5B7B6D] flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span>"TribeWellMD Community donated $X this month" messaging</span>
                  </li>
                </ul>

                <div className="p-5 bg-gradient-to-br from-[#F5F0E8] to-[#E8E0D5] dark:from-[#5B7B6D]/20 dark:to-[#2D5A4A]/20 rounded-xl border border-[#D4C4B0] dark:border-[#8B7355]">
                  <h4 className="font-medium text-slate-900 dark:text-white mb-2">Future: Student-Created Projects</h4>
                  <p className="text-sm text-slate-600 dark:text-slate-400">
                    "Micro-grants" model where students propose community health projects. Community votes with village points.
                    Top projects get funded. Creates incredible engagement and real-world impact.
                  </p>
                </div>

                <div className="mt-4 p-5 bg-slate-100 dark:bg-slate-800 rounded-xl">
                  <h4 className="font-medium text-slate-900 dark:text-white mb-2">Custom Charity Option</h4>
                  <p className="text-sm text-slate-600 dark:text-slate-400">
                    Users can suggest charities for consideration. All submissions must be 501(c)(3) verified and undergo admin approval
                    to ensure alignment with our mission and prevent inappropriate causes.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Contact CTA */}
        <section ref={contactRef} className="bg-gradient-to-br from-[#5B7B6D] to-[#2D5A4A] text-white py-16 md:py-24">
          <div className={`max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center transition-all duration-700 ${contactVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
            <div className="w-16 h-16 mx-auto mb-6 rounded-2xl bg-white/20 flex items-center justify-center text-white">
              <Icons.Contact />
            </div>
            <h2 className="font-serif text-3xl md:text-4xl font-bold mb-4">
              Partner With Us
            </h2>
            <p className="text-[#E8E0D5] text-lg mb-8 max-w-2xl mx-auto">
              Join our network of charity partners and receive donations from medical students who are investing in their future
              while making a difference today.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <a
                href="mailto:partners@tribewellmd.com"
                className="px-8 py-4 bg-gradient-to-r from-[#C4A77D] to-[#A89070] text-white font-bold rounded-xl hover:shadow-xl transition-all shadow-lg"
              >
                Contact Us: partners@tribewellmd.com
              </a>
              <Link
                href="/investors"
                className="px-8 py-4 border-2 border-white/50 text-white font-semibold rounded-xl hover:bg-white/10 transition-all"
              >
                For Investors →
              </Link>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
